DROP FUNCTION IF EXISTS check_usage_limit(INTEGER, VARCHAR);
DROP FUNCTION IF EXISTS get_usage_summary(INTEGER);
DROP FUNCTION IF EXISTS record_usage_event(INTEGER, VARCHAR, INTEGER, INTEGER, JSONB);
DROP FUNCTION IF EXISTS get_or_create_usage_period(INTEGER, VARCHAR);
DROP TABLE IF EXISTS usage_events;
DROP TABLE IF EXISTS usage_periods;
